# Generated by Django 5.1.4 on 2024-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
